first_app/urls.py
from django.contrib import admin
from django.conf.urls import url
from first_app import views
app_name='first_app'
urlpatterns = [
    url(r'^register/',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
]

rishi/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from first_app import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^first_app/',include('first_app.urls')),
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^special/$',views.special,name='special'),
]

urlpatterns += staticfiles_urlpatterns()

first_app/models.py
from django.contrib.auth.models import User
from django.db import models
from datetime import datetime, date, timedelta

first_app/forms.py
from django import forms
from django.contrib.auth.models import User
class Userform(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)
    class Meta():
        model = User
        fields = ('username','email','password')

first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from first_app.forms import Userform
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from first_app.models import Fine, User
from datetime import date
# Create your views here.

def index(request):
    return render(request, 'first_app/index.html')

def register(request):
    registered  = False
    if request.method == "POST":
        user_form=Userform(data=request.POST)
        if user_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
        else:
            print(user_form.errors)
    else:
        user_form = Userform()
    return render(request,'first_app/registration.html',{'user_form':user_form,
                                                         'registered':registered})

def user_login(request):
    if request.method == "POST":
        username=request.POST.get('username')
        password=request.POST.get('password')
        user = authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                fines=Fine.objects.all()
                args={'fines':fines}
                return render(request, 'first_app/fine.html',args)
            else:
                return HttpResponse("Account not active")
        else:
            print("Someone tried to login and failed")
            print("Username{} and password{}".format(username,password))
            return HttpResponse("Invalid login details")
    else:
        return render(request, 'first_app/login.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("You are logged in")

templates/first_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
    <style>
            ul {
      list-style-type: none;
      margin: 0;
      padding: 0;
      overflow: hidden;
      background-color: #333;
    }

    li {
      float: left;
    }

    li a {
      display: block;
      color: white;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
    }

    /* Change the link color to #111 (black) on hover */
    li a:hover {
      background-color: #111;
    }
    </style>
</head>
<body>
    <nav class='navbar navbar-default navbar-static-top'>
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index' %}">HOME</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">ADMIN</a></li>

                {% if user.is_authenticated %}
                    <li><a class="navbar-link" href="{% url 'logout' %}">LOGOUT</a></li>
                {% else %}
                    <li><a class="navbar-link" href="{% url 'first_app:register' %}">REGISTER</a></li>
                    <li><a class="navbar-link" href="{% url 'first_app:user_login' %}">LOGIN</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body-block %}
        {% endblock %}
    </div>
</body>
</html>

templates/first_app/fine.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ user.username}}</title>
    <style >
		table,th,td{
			border: 3px solid black;
		}
		td{
			text-align: center;
		}
		table{
			border-collapse: collapse;
		}
	</style>

</head>
<body>
    <h1>Welcome {{ user.username }} to your library books dashboard </h1>
    <table style="width:100%">
        <tr>
            <!-- <th><h2>S No.</h2></th> -->
            <th><h2>Book Name</h2></th>
            <th><h2>Book_id</h2></th>
            <th><h2>Issue Date</h2></th>
            <th><h2>Due Date</h2></th>
            <th><h2>Fine</h2></th>
        </tr>
        {% for fine in fines %}
            {% ifequal fine.user_name.username user.username %}
                <tr>
                    <!-- <td>{{ fine.id }}</td> -->
                    <td>{{ fine.book }}</td>
                    <td>{{ fine.book_id }}</td>
                    <td>{{ fine.issue_date }}</td>
                    <td>{{ fine.tplus }}</td>
                    <td>{{ fine.total }} Rs.</td>
                </tr>
            {% endifequal %}
        {% endfor %}
    </table>

</body>
</html>

templates/first_app/form_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div class="container">
        <form method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="submit">
        </form>
    </div>

</body>
</html>

templates/first_app/index.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% block body-block %}
<head>
  <style>
*{
    margin: 0;
    padding: 0;
}
  
.text-box{
    font-size: 70px;
    font-family: sans-serif;
    position: absolute;
    top:40%;
    left: 40%;
    transform: translate(-50%,-50%);
}
span{
    animation: mover 2s linear infinite;
    display: inline-block;
    color: rgb(255, 255, 255);
    font-weight: bolder;
}
@keyframes mover
{
    0%{
        text-shadow: 0 0 30px rgba(0, 0, 0, 0);
      }
    50%{
        text-shadow: 0 0 30px rgba(0, 0, 0, 0.30);
        transform: translateY(30px);
      }
    100%
      {
        text-shadow: 0 0 30px rgba(0, 0, 0, 0);
      }
}
span:nth-child(1)
{
    animation-delay: 0.5s;
}
span:nth-child(2)
{
    animation-delay: 1s;
}
span:nth-child(3)
{
    animation-delay: 1.5s;
}
span:nth-child(4)
{
    animation-delay: 2s;
}
span:nth-child(5)
{
    animation-delay: 2.5s;
}
span:nth-child(6)
{
    animation-delay: 3s;
}
span:nth-child(7)
{
    animation-delay: 3.5s;
}

div{
  text-align: center;
}
</style>
</head>
<html>
<head>  
<title>Animated Text</title>
<link rel="stylesheet" href="style.css">
</head>
<body background="https://wallpaperaccess.com/full/2964938.jpg">
    
    
    <div class="text-box">
    <span>WELCOME</span>
    <span>TO</span>
    <span>LIBRARY</span>
    <span>FINE</span>
    <span>PROJECT</span>
    </div>
</body>
</html>
{% endblock %}

templates/first_app/login.html
{% extends 'first_app/base.html' %}
{% block body-block %}
<head>
    <style>
input[type=text], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}
input[type=password], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=submit] {
  width: 100%;
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

div {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}
h1{
  text-align: center;
}
</style>
</head>
<div class="jumbotron">
    <h1>Login Page</h1>
    <form action="{% url 'first_app:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username</label>
        <input type="text" name="username" placeholder="Enter Username">
        <label for="password">Password</label>
        <input type="password" name="password">
        <input type="submit" value="Login">
    </form>
</div>
{% endblock %}

templates/first_app/registration.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}
{% block body-block %}
<head>
    <style>
input[type=text], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}
input[type=email], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}
input[type=password], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=submit] {
  width: 100%;
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

div {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}
h1{
    text-align: center;
}
</style>
</head>
<div class="jumbotron">
    {% if registered %}
        <h1>Thank u for registering</h1>
    {% else %}
        <h1>REGISTRATION PAGE</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{user_form.as_p}}
            <input type="submit" value="Register">
        </form>
    {% endif %}
</div>
{% endblock %}